### ISSUE TITLE
[QUESTION] Is it possible to display the innings with the StatsAPI?

### ISSUE THREAD

**Issue by ABUCKY0** [toddrob99/MLB-StatsAPI#106]

**Comment by toddrob99** [comment]
You can find inning data (e.g. to build a linescore) in the [game endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-game). You'll find it in the response under `game["liveData"]["linescore"]`.

```python
game = statsapi.get("game", {"gamePk": 719124})
linescore_data = game["liveData"]["linescore"]
```

If linescore is what you're after, you can also get a formatted linescore using this library's [linescore method](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-linescore). You can see how this method retrieves and parses the data [here](https://github.com/toddrob99/MLB-StatsAPI/blob/master/statsapi/__init__.py#L832)
