### ISSUE TITLE
Anyway to retrieve Play by play data

### ISSUE THREAD

**Issue by cruzjon2024** [toddrob99/MLB-StatsAPI#108]

**Comment by toddrob99** [comment]
Yes, use [statsapi.get()](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-get) with the [game endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-game).

There's a little more info about the path within the API response in #90. Basically look under `liveData` for `allPlays`.
