### ISSUE TITLE
statsapi.lookup_team('San Fransisco Giants') is giving the wrong Team Code

### ISSUE THREAD

**Issue by romanbogza** [toddrob99/MLB-StatsAPI#11]
'teamCode' for this call (statsapi.lookup_team('San Fransisco Giants')) is SFN instead of SFG - can you explain why that is?

**Comment by toddrob99** [comment]
Team code is a field that MLB maintains, and for teams with a two-letter abbreviation or a city with both NL and AL teams, they use N or A for the third character of the team code. Other examples are NYA for Yankees, NYN for Mets, CHA for White Sox, CHN for Cubs, TBA for Rays, etc.

Have a look at the source data for the lookup_team() function: https://statsapi.mlb.com/api/v1/teams?sportIds=1. 

You may be more interested in the file code or abbreviation (both SF for the Giants). Check out the differences for the Cardinals, as another example:

    "teamCode" : "sln",
    "fileCode" : "stl",
    "abbreviation" : "STL"

**Comment by toddrob99** [comment]
This might be an even better example of how these fields don't always line up:

```
"team" : {
        "id" : 119,
        "name" : "Los Angeles Dodgers",
        "link" : "/api/v1/teams/119",
        "teamCode" : "lan",
        "fileCode" : "la",
        "abbreviation" : "LAD",
```
