### ISSUE TITLE
Way to obtain gamePk for current game?

### ISSUE THREAD

**Issue by unnes** [toddrob99/MLB-StatsAPI#112]
Super cool library. It's been getting me back into playing with Python and I'm very grateful for that.

statsapi.last_game works great to pull the most completed game, but is there a way to pull a currently-active game? One of the help pages implied that last_game should but it seems like its not. Is there a function that I'm missing?

**Comment by toddrob99** [comment]
Use the [schedule function](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-schedule) and pass in the current date and team id. That will return today's games for the given team, and you can check the status to see if it's currently active. Note there could be more than one game listed, in case of a doubleheader.

**Comment by unnes** [comment]
Fantastic! Thanks for the direction and I appreciate the caveat about doubleheaders.
