### ISSUE TITLE
team stats

### ISSUE THREAD

**Issue by gjj07** [toddrob99/MLB-StatsAPI#113]
is there a function to get pitcher stats and team stats by year? Thank you

**Comment by toddrob99** [comment]
For team stats, use [statsapi.get()](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-get) with the [stats endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-stats). The available `statType`s are available with `statsapi.meta("statTypes")` -- you may be interested in `season`. There are examples on [reddit](https://reddit.com/r/mlbdata) and probably in the closed issues in this repo.

For player stats, you can use [statsapi.player_stat_data()](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-player_stat_data).
