### ISSUE TITLE
Standings_data division parameter should accept divisionId instead of only abbreviation

### ISSUE THREAD

**Issue by justintran12** [toddrob99/MLB-StatsAPI#115]
Here is the documentation for the function:
statsapi.standings_data(leagueId="103,104", division="all", include_wildcard=True, season=None, standingsTypes=None, date=None).
Doing statsapi.standings_data(division = "200") or statsapi.standings_data("103", "200") returns empty dict.

I found I can just do this statsapi.standings_data(leagueId = "103")[200]) to get the division standings, so it's not a big deal, but just wanted to document the issue.

**Comment by SigireddyBalasai** [comment]
i want to work on this

**Comment by jimcreel** [comment]
I submitted a pull request for this enhancement if the issue is still available.

**Comment by toddrob99** [comment]
released in v1.6.2
