### ISSUE TITLE
Return line score when using schedule end point

### ISSUE THREAD

**Issue by arihani2** [toddrob99/MLB-StatsAPI#118]
When reading the wiki, I saw that there was a way to retrieve the linescore for a game by adding the hydrate=linescore parameter into the call. I have tried some variants of this and all result in a Type error since hydrate is not an argument to the function. I looked at the source code and it doesn't seem that there is functionality to include the line score in this call. Can this be made possible or is it already possible and I am reading the code wrong/inputting the argument wrong.

**Comment by toddrob99** [comment]
The functions built into this module don't support all features of the API. They are meant to cover some basic use cases, and show examples of how to use [statsapi.get()](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-get) for more advanced cases.

If you're using the [schedule function](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-schedule), you can see the support parameters and example output at that wiki link. You can see how that function builds the parameters and makes the API call [here](https://github.com/toddrob99/MLB-StatsAPI/blob/78b2ae1fb986a6bfd49e81d4e50a6f3e1d7278e2/statsapi/__init__.py#L61-L94). This is what you would want to duplicate and modify to include the hydration(s) you want.

**Comment by arihani2** [comment]
Got it, thank you. I appreciate your help
