### ISSUE TITLE
league leaders function giving some errors

### ISSUE THREAD

**Issue by pwu97** [toddrob99/MLB-StatsAPI#12]
i was going through some of the code in the documentation:

this line of code:
print( statsapi.league_leaders('onBasePlusSlugging',statGroup='hitting',limit=5) )

gives:
IndexError: list index out of range

**Comment by toddrob99** [comment]
I just noticed this last night. Apparently StatsAPI stopped supporting the statType of statsSingleSeason. I have made changes to pull career leaders in the examples instead, since I no longer see a way to pull single season record holders. I need to do some more testing before publishing.

**Comment by toddrob99** [comment]
Please update to v0.1.0 via `pip install --update MLB-StatsAPI` and thank you for reporting the issue
