### ISSUE TITLE
TypeError: Teamrecords.__init__() got an unexpected keyword argument 'eliminationnumbersport'

### ISSUE THREAD

**Issue by martinmccarthy** [toddrob99/MLB-StatsAPI#120]
Looks like the MLB API was updated, this was the call I was doing:
`    current_al_standings = mlb.get_standings(league_id = 103, season = 2023)`

**Comment by toddrob99** [comment]
Are you importing `statsapi` or `mlbstatsapi`? They are two different packages. This repository is for `statsapi`.

**Comment by martinmccarthy** [comment]
Ah good catch, apologies for that
