### ISSUE TITLE
Incorrect seasons endpoint documentation

### ISSUE THREAD

**Issue by ntbanks** [toddrob99/MLB-StatsAPI#128]
Love this wiki and this package, awesome work on this!. I prefer to make HTTP calls directly and got stuck for a while because of the incorrect documentation for the `seasons` end point. Here is how to correctly call the seasons end point:
- All seasons: `http://statsapi.mlb.com/api/v1/seasons/all?sportId=1`

While the docs make it seem like you would call it like this... or something...?, which gives an error:
- All seasons: `http://statsapi.mlb.com/api/v1/seasons/True?sportId=1`  

So... there is a missing `/` after `seasons`, and the wording around `all` being a boolean is very confusing. 

Mostly posting this to help confused people not to get the docs fixed. 

Cheers!

**Comment by toddrob99** [comment]
I can see how this is confusing. The way the endpoint documentation is written in the wiki is how this api wrapper builds the URLs. For the `seasons` endpoint, it has a "path parameter" named `all`, which is a boolean that will add `/all` to the path if passed with a value of `True`. You can see the logic in [endpoints.py](https://github.com/toddrob99/MLB-StatsAPI/blob/b67ef0ac6f9b83f6532bdb63515b4dca1310dc39/statsapi/endpoints.py#L870C21-L870C21). 

I have updated the wiki to be a bit more clear around the usage of this endpoint.

**Comment by ntbanks** [comment]
Ohhhh! Duh ok that makes sense, I missed that. Thanks for the explanation and updating the wiki
