### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by thomasthaddeus** [toddrob99/MLB-StatsAPI#135]
There are typos in the wiki. Mostly just letters in reverse order

**Comment by toddrob99** [comment]
Can you be more specific?

**Comment by toddrob99** [comment]
I found `Pyhton` on the logging page. If you saw others, please give me more details and I'll be happy to fix them.

**Comment by thomasthaddeus** [comment]
@toddrob99 
Yeah sorry about that I made the issue on my phone, I'll make sure to add the rest today.

**Comment by thomasthaddeus** [comment]
I must have been mistaken so I'm closing this issue. I might have been on another page seeing typos.
