### ISSUE TITLE
Get Team Mark

### ISSUE THREAD

**Issue by webdeveloper1016** [toddrob99/MLB-StatsAPI#136]
Hello,
I am using MLB Stats API. I am goging to get url of team mark image.
How can I do this?

**Comment by toddrob99** [comment]
I don't think logos are available through the official MLB StatsAPI endpoints. You might be able to find another API that has them, such as ESPN. I think there was a post on https://reddit.com/r/mlbdata about it recently.

**Comment by Iliannnn** [comment]
https://www.reddit.com/r/mlbdata/comments/1b1eit0/team_logos/
