### ISSUE TITLE
Extra Games in Schedule

### ISSUE THREAD

**Issue by Haglothor** [toddrob99/MLB-StatsAPI#137]
When pulling the game ids for a season within the opening day and last day of regular season for 2023 season, I am getting more than 162 games for some teams.
`schedule = statsapi.schedule(team=id[1], start_date='03/30/2023', end_date='10/02/2023')`
![image](https://github.com/toddrob99/MLB-StatsAPI/assets/157931443/b574e823-21db-440c-b4e6-ac2e58817702)
Every team has at least 162 games and opening day game ids match, but some teams the last game of regular season is not in the 162nd spot. Any idea on how to fix this?

**Comment by toddrob99** [comment]
Check the number of unique game ids, along with game status and original game date. Most likely you're counting postponed games more than once.

**Comment by Haglothor** [comment]
That worked, thank you!
