### ISSUE TITLE
The divisions endpoint allows 'season' as an optional endpoint.

### ISSUE THREAD

**Issue by BranchRickey** [toddrob99/MLB-StatsAPI#141]
Minor issue, but the divisions endpoint does allow 'season' as a valid optional parameter.  The following URL produces the divisions for the 1984 season:

http://statsapi.mlb.com/api/v1/divisions?season=1984

This is useful if you are building a database with historical information.

**Comment by toddrob99** [comment]
I will add the season param to the divisions endpoint, and in the meantime you can use the `force` param to make the wrapper include it in your [get](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-get) calls.
