### ISSUE TITLE
Thanks Todd!

### ISSUE THREAD

**Issue by AlecM33** [toddrob99/MLB-StatsAPI#144]
Hey Todd - I've been working on my own project using the stats API and JavaScript. Just wanted to say thanks for your documentation of the MLB stats API, as well as some of your replies on the mlbdata subreddit which I stumbled across during development. It definitely helped me piece together some of the less intuitive parts of the API's usage. If you're interested in seeing the project, it's at: https://github.com/AlecM33/mlb-gameday-bot

That's it! :) Feel free to close or delete this issue.

**Comment by toddrob99** [comment]
I am really happy you found the documentation helpful! Your project looks great. Like I commented on your Reddit post, my only suggestion would be to package the app in a docker image to make it easier for other people to run it. That way they won't run into environmental issues.
