### ISSUE TITLE
Use HTTPError instead of ValueError for HTTP errors?

### ISSUE THREAD

**Issue by dowski** [toddrob99/MLB-StatsAPI#46]
I [noticed](https://github.com/dowski/scoreboard/issues/8) that if I call StatsAPI's `get` method and the server returns a 5xx error, the StatsAPI code raise a `ValueError`.

Would you be open to allowing Requests to raise an `HTTPError` instead? It's directly [supported](https://requests.readthedocs.io/en/master/user/quickstart/#response-status-codes) by the Requests API:

```
r.raise_for_status()
```

I think that the `HTTPError` would make it more clear to callers what went wrong. If it sounds good I'll send a small pull request.

**Comment by toddrob99** [comment]
That makes sense to me. Go for it!
