### ISSUE TITLE
player_stats_data throws KeyError when Debut Date not returned by statsapi.mlb.com

### ISSUE THREAD

**Issue by mycarda** [toddrob99/MLB-StatsAPI#49]
**Steps to recreate:**
call statsapi.player_stat_data( 592622, group="hitting", type="season") for player Mark Payton with id 592622
Data can be seen directly at https://statsapi.mlb.com/api/v1/people/592622?hydrate=stats(group=hitting,type=season),currentTeam

**Expected result:**
Data returned

**Actual result:**
File "/home/mycarda/.local/lib/python2.7/site-packages/statsapi/__init__.py", line 1123, in player_stat_data
    "mlb_debut": r["people"][0]["mlbDebutDate"],
KeyError: 'mlbDebutDate'

**Comment by toddrob99** [comment]
Fixed in v1.0.1

`python -m pip install --upgrade mlb-statsapi`

Thank you

**Comment by mycarda** [comment]
I did not expect a fix that quickly. Just upgraded to v1.0.1 and the fix works perfectly. Thank you.
