### ISSUE TITLE
Which endpoint contains inning data?

### ISSUE THREAD

**Issue by 802GrnMtnBoy** [toddrob99/MLB-StatsAPI#51]
Hi there,
Thank you so much for this module. I really enjoy using it.
Wondering if you could tell me which endpoint contains inning related data i.e. number of outs, current batter, type of hit (single vs. double, etc.)
Thanks so much

**Comment by toddrob99** [comment]
The [Game](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-game) endpoint contains that info. 

`statsapi.get("game", {"gamePk": 641558})`

That will pull data from https://statsapi.mlb.com/api/v1.1/game/641558/feed/live.

Search for liveData.

**Comment by toddrob99** [comment]
Feel free to comment again if you need anything additional. I'm going to close the issue.
