### ISSUE TITLE
Make additional standings ranks available

### ISSUE THREAD

**Issue by Amorymeltzer** [toddrob99/MLB-StatsAPI#52]
It'd be nice to have the option of getting `leagueRank` and `sportRank` when getting standings, but right now `standings_data` doesn't even pull that data.  Having it in `standings`—perhaps with a flag or only when getting just one league/the whole sport—would be ideal, but at a minimum making it available via `standings_data` would be fine.

**Comment by toddrob99** [comment]
I'll add `leagueRank` and `sportRank` to the data returned by `standings_data()` in v1.1, but I don't intend to add those fields to the formatted text returned by `standings()`.

Keep in mind you can always copy any of the built-in methods and modify however you see fit. Most of the built-in methods are just intended to cover some common use cases, and to give examples of how to work with the API.

**Comment by Amorymeltzer** [comment]
Perfect, thanks!
