### ISSUE TITLE
Add a note for the default 50 record limit for the STATS endpoint. *Low Priority*

### ISSUE THREAD

**Issue by mjstamper** [toddrob99/MLB-StatsAPI#54]
When pulling from the STATS endpoint, it has a default limit of 50 records.  Adding a note for the STATS endpoint to declare the default 50 record limit will help clarify returned data.

**Comment by toddrob99** [comment]
Sure, I'll add a note:

>If no limit is specified, the response will be limited to 50 records.

**Comment by toddrob99** [comment]
Added to v1.3. Thanks for the suggestion.
