### ISSUE TITLE
How do I determine what options are available for "fields" and "hydrate"?

### ISSUE THREAD

**Issue by matthewncorrado** [toddrob99/MLB-StatsAPI#56]
Were these originally determined through trial and error, or is there somewhere I can go for more information about how to use these parameters for different endpoints?

**Comment by toddrob99** [comment]
There is documentation, but it requires a login which only MLB affiliates have. One way I've had success is finding somewhere on the MLB website that has the data I want and viewing the network log in my browser's developer tools. You can filter on statsapi.mlb.com to see the API calls with their full URLs. That is how I learned about hydrations. There are also a bunch of questions/answers on the [r/mlbdata subreddit](https://reddit.com/r/mlbdata) that might help, and you can post there for help with anything you can't find.

**Comment by toddrob99** [comment]
For `fields`, request the full data (exclude the fields parameter) to see all fields. Then if you only want a subset of the fields, include the fields parameter with a comma-separated list of the ones you want. There are some examples of usage in this repo along with the r/mlbdata.
