### ISSUE TITLE
[Request] Add national broadcast information to `schedule` data

### ISSUE THREAD

**Issue by WardBrian** [toddrob99/MLB-StatsAPI#71]
It's possible to get information about where a game is being broadcast from the schedule endpoint:

 https://statsapi.mlb.com/api/v1/schedule?sportId=1&date=2022-04-10&hydrate=broadcasts

Especially with all the new services, it would be great to include national broadcasts in the `schedule()` method's return data. I don't think non-national would be that valuable, since it will usually be the same network

**Comment by toddrob99** [comment]
v1.5 is published to pypi now
