### ISSUE TITLE
Is there a function for current game? 

### ISSUE THREAD

**Issue by jcsacto** [toddrob99/MLB-StatsAPI#72]
First off, thank you for this app, it's exactly what I was looking for to display my SF Giants stats on my TV dashboard.   I thought I could use the next_game function to show scores as the game is played (since it has a spot for home/away scores).  But that doesn't appear to be the case.  Is there an easy way to get the current game ID to pass to the one of the other game stats functions?  Thanks again!

**Comment by toddrob99** [comment]
You can get today's gamePk(s) from the [schedule endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-schedule) using the [get method](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-get) or the [schedule method](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-schedule). Either way, pass your team id and date, and grab the gamePk/game_id from the result. The schedule method might even return all the info you want.

**Comment by jcsacto** [comment]
Ok, that works easy enough, I should have tried that prior to asking. :) Thanks again!
