### ISSUE TITLE
There is no documentation for the terms params for each function.

### ISSUE THREAD

**Issue by ABUCKY0** [toddrob99/MLB-StatsAPI#75]
I am personally unable to find the gamePk parameter documentation.

**Comment by toddrob99** [comment]
MLB has not made the StatsAPI documentation public, but I have documented a lot in this repository's [wiki](https://github.com/toddrob99/MLB-StatsAPI/wiki). If you have specific questions I suggest posting them on [r/mlbdata](https://reddit.com/r/mlbdata). You might also find what you need by searching there.
