### ISSUE TITLE
Unable to get local issuer certification

### ISSUE THREAD

**Issue by roe-men** [toddrob99/MLB-StatsAPI#76]
I installed MLB Stats API to my Windows laptop but having issues accessing the API when coding. Any ideas on how to fix the below error?

_CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate_

**Comment by toddrob99** [comment]
That error is not specific to the MLB-StatsAPI module. Does your network require a proxy server? You might need to search Google for the error message to find a solution.

**Comment by roe-men** [comment]
thanks, was an issue with my local drive. decided to just move to collab for simplicity and to store in cloud.
