### ISSUE TITLE
Today's game date

### ISSUE THREAD

**Issue by roe-men** [toddrob99/MLB-StatsAPI#77]
How would you pull today's scheduled game date?

I'm working on a Twitter bot to tweet live updates from Mets games but having issues with the currently defined functions and creating variables off of them. For example get_next_game function would only work as a reference point until the first pitch is thrown. So essentially I need to create a variable with today's gamePk and not the next_game. 

I've tried using the get function to pull the startTimecode with no success. 

Sorry if this is a simple fix, very new to the coding game.

**Comment by toddrob99** [comment]
Use the [schedule function](https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-schedule):

```
today_schedule = statsapi.schedule()
```

Or get raw data from the [schedule endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-schedule). 

```
today_schedule = statsapi.get("schedule", {"sportId": 1})
```
