### ISSUE TITLE
Pitches per inning

### ISSUE THREAD

**Issue by apelt001** [toddrob99/MLB-StatsAPI#81]
Is there an easy way to get pitches per inning for a given gamePk? I can't seem to find out which timecodes correspond to end of innings.

**Comment by apelt001** [comment]
Wow this is great, thank you. What about if I just want pitch count per inning by pitcher. Would I have to code that up myself?

**Comment by toddrob99** [comment]
I think so... It has total pitches for each pitcher, but not broken down by inning as far as I have seen.
