### ISSUE TITLE
How to get game_log for a player?

### ISSUE THREAD

**Issue by ForceConstant** [toddrob99/MLB-StatsAPI#86]
How can I get game_log for a specific player for a specific game? i.e. hits, or pitching stats for pitchers.

Thanks.

**Comment by toddrob99** [comment]
If you want a player's stats for a given game, I would use the [game endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-game). Player stats are in the boxscore: liveData > boxScore > teams > {home/away} > players > {personId} > stats

**Comment by ForceConstant** [comment]
Thanks
