### ISSUE TITLE
Additional Data?

### ISSUE THREAD

**Issue by jouellnyc** [toddrob99/MLB-StatsAPI#90]
Howdy. Great Library. I've taken a look here and can collect data for current balls/strikes/outs  just fine (thanks for that) but cannot see data for example for the final decision of the at bat (i.e 'walk' , 'hit to left', 'home run' / etc ). Is that possible?

Or how if runners are on base, which bases. Would that be possible?

I am happy to help but am not yet familiar w/the upstream components.

**Comment by toddrob99** [comment]
That data is in the [game endpoint](https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints#endpoint-game). Each item in the list at `liveData` > `plays` > `allPlays` has a `result` dict that contains the outcome of the play, a `runners` list that shows all runner movement, and a `playEvents` list that contains all events in the play.

**Comment by jouellnyc** [comment]
Ah. I misunderstood. I thought I had poked this enough. Sorry 'bout that. And thank you for the pointer.
