### ISSUE TITLE
404 Client Error - team_stats Endpoint

### ISSUE THREAD

**Issue by Laneville** [toddrob99/MLB-StatsAPI#92]
Getting an HTTPError: 404 Client Error: Not found for url:
https://statsapi.mlb.com/api/v1/teams/159/stats?season=2022&group=hitting

Can someone confirm if they are experiencing the same issue with this 'team_stats' endpoint?

<img width="1019" alt="Screen Shot 2022-08-14 at 2 59 36 PM" src="https://user-images.githubusercontent.com/19177503/184551127-cff15d1c-d562-491b-9ed6-e3fb9398e603.png">

**Comment by Laneville** [comment]
I have submitted an application to statsapi MLB for their documentation so hopefully I can troubleshoot this error and help out, instead of just posting :)

**Comment by toddrob99** [comment]
> I have submitted an application to statsapi MLB for their documentation so hopefully I can troubleshoot this error and help out, instead of just posting :)

You won't get access to the MLB documentation unless you're an affiliate.

**Comment by toddrob99** [comment]
I think there are two issues here... 

1. The `stats` parameters was not indicated as required in the documentation when I generated this package's endpoint structure, but it does in fact appear to be required. If you include `stats=season` the endpoint works. Try https://statsapi.mlb.com/api/v1/teams/143/stats?season=2022&group=hitting&stats=season or `statsapi.get("team_stats", {"teamId": 143, "season" : 2022, "group": "hitting", "stats": "season"})`
2. You are using teamId 159 which is AL All-Stars. It appears this team is not valid for team_stats. https://statsapi.mlb.com/api/v1/teams/159/stats?season=2022&group=hitting&stats=season still returns the 404 error message.

**Comment by Laneville** [comment]
yes, looks like I got that response from MLB :(

And yes looks like that fixed the issue. Thank you!
