### ISSUE TITLE
gameType param not working for sports_players endpoint?

### ISSUE THREAD

**Issue by Yurockkk** [toddrob99/MLB-StatsAPI#94]
Hi Todd,

Thanks for this very convenient wrapper library! I'm trying to get a list of players who made it to the post season and using the `sports_players` endpoint with `gameType` set to `P` (Playoffs). However, It doesn't seem to care about this param and always return the same result... for example:

pass in `R` (Regular Season), it returns 1539 players:

```
statsapi.get('sports_players', 
    {
        'season':2022,
        'gameType': 'R',
        'ver': 'v1',
        'sportId': 1
    }).get('people')
```

pass in `P` (Playoffs), it also returns 1539 players...:

```
statsapi.get('sports_players', 
    {
        'season':2022,
        'gameType': 'P',
        'ver': 'v1',
        'sportId': 1
    }).get('people')
```

Any workaround to fetch this player list?

Thank you.

**Comment by toddrob99** [comment]
Interesting... You're right, the gameType param doesn't do anything. It's in the old copy of the documentation I have as a reference, but even the example given in the documentation doesn't work. It gives the example of https://statsapi.mlb.com/api/v1/sports/1/players?season=2017&gameType=W but that returns the same number of players as gameType=R for 2017. I guess you could find the teams in the postseason from the schedule endpoint and get the players for each team. Not sure if there's a straightforward workaround.

**Comment by Yurockkk** [comment]
Alright, I'll try to get it from `schedule_postseason` endpoint and will share here if I found a straightforward workaround 

Thanks!

**Comment by toddrob99** [comment]
Please do, and I'll close for now.
